# Credit Risk Modeling Using Machine Learning

## Banking Termninoligies

### Asset

- **Asset is something that can give some profit to bank finally. (Bank favour)**
- Known as Loan Product
#### Examples
- Housing loan

- Personal loan

- Vehicle loan

- Group loan

- Education loan

- Credit Card

### Liability

- **Liability is something that can give some Loss to bank finally. (Customer favour)**
#### Examples
- Current account

- Savings account

- Fixed deposit

- Recurring Deposit

- Term Deposits

### NPA

- **Non Performing Asset**
- Loan that is defaulted
- Loan account when DPD > 90 days

### Net Non-Performing Assets (NNPA)

**Definition:** NNPA represents the portion of a bank's non-performing assets (NPAs) that remains after deducting provisions set aside for potential losses.

**Calculation:** NNPA = Gross NPAs - Provisions

**Significance:** NNPA gives a more accurate view of a bank's financial health regarding bad loans because it shows the actual potential losses if borrowers default on their NPAs.

**Example:**
Let's say a bank has the following figures:
- Gross NPAs (total value of NPAs): $10 million
- Provisions (reserve funds for potential losses): $3 million

NNPA = $10 million - $3 million = $7 million

This means the bank has $7 million of NPAs after considering provisions.

### Gross Non-Performing Assets (GNPA)

**Definition:** GNPA represents the total value of a bank's non-performing assets (NPAs) before accounting for any provisions.

**Calculation:** GNPA = Total value of all NPAs (Substandard, Doubtful, and Loss Assets)

**Significance:** GNPA provides a broad picture of a bank's asset quality and the overall level of stressed loans on its books.

**Example:**
Suppose a bank has the following NPAs in different categories:
- Substandard Assets: $5 million
- Doubtful Debts: $3 million
- Loss Assets: $2 million

GNPA = $5 million (Substandard) + $3 million (Doubtful) + $2 million (Loss) = $10 million

This means the bank has $10 million of NPAs before considering any provisions.

### Loan Classification Stages

Let's now explore the stages of loan classification from Days Past Due (DPD) to Write-Off:

1. **DPD (Days Past Due):**
   - **Definition:** DPD refers to the number of days a borrower has exceeded the due date for a loan payment.
   - **Example:** If a borrower's monthly loan payment is due on the 1st of each month and they miss the payment, they enter DPD status. For instance, if the current date is the 15th and the borrower hasn't made the payment, they are 15 days past due.

2. **Non-performing Asset (NPA):**
   - **Definition:** A loan becomes an NPA if the borrower misses payments for a specific period, often 90 days or more.
   - **Example:** If a borrower hasn't made any payments for 90 days on a loan, it is classified as an NPA.

3. **Special Mention Account (SMA):**
   - **Definition:** SMA refers to loans identified by banks as having a high potential of turning into NPAs.
   - **Example:** A loan with consistent delays in payments or signs of financial stress from the borrower may be categorized as SMA.

4. **Write-off:**
   - **Definition:** A loan is written off when the bank deems it unrecoverable and removes it from active accounts.
   - **Example:** If all attempts to recover a loan fail, such as through legal actions or negotiations, the bank may decide to write off the loan as a loss.

Understanding these stages helps banks manage risks associated with loans and take appropriate actions to recover funds or minimize losses.

### Disbursed Amount

- DA is a amount given to a customer as loan

### OSP

- **Out Standing Principle**
- In simple words OSP is the amount that is remaining to return the loan to bank
- OSP should be zero at the end of loan cycle

### DPD

- **Days Past Due**
- **Defaulted** if $DPD > 0$

### PAR

- **Portfolio At Risk**
- OSP when DPD > 0

## Credit Risk Types in Banking

- DPD (Zero) : NDA (Non delinquint account) = No default account = Timely payment EMI

- DPD (0 to 30) : SMA1 (Standard Monitoring Account)

- DPD (31 to 60) : SMA2 (Standard Monitoring Account)

- DPD (61 to 90) : SMA3 (Standard Monitoring Account)

- DPD (90 to 180) : NPA
- DPD (>180) : Writen-off (Loan which is not present)

**NNPA (Net Non-Performing Assets)**

* **Definition:** This represents the portion of a bank's non-performing assets (NPAs) remaining *after* deducting provisions set aside for potential losses. Provisions are like reserve funds created by banks to anticipate losses on bad loans.
* **Calculation:** 
    NNPA = Gross NPAs â€“ Provisions
* **Significance:** NNPA is a more accurate measure of a bank's true financial health with regards to bad loans. It shows the actual potential losses the bank might face if borrowers completely default on their NPAs.

**GNPA (Gross Non-Performing Assets)**

* **Definition:** This represents the total value of a bank's non-performing assets (NPAs) *before* accounting for any provisions.
* **Calculation:**
    GNPA =  Total value of all NPAs (Substandard, Doubtful, and Loss Assets)
* **Significance:** GNPA offers a broader picture of a bank's asset quality and the overall level of stressed loans on its books.

**Markdown Table**

| Metric | Definition | Calculation | Significance |
|---|---|---|---|
| GNPA (Gross Non-Performing Assets) | Total value of NPAs before provisions |  Total value of all NPAs (Substandard, Doubtful, Loss Assets) | Indicates overall level of stressed loans|
| NNPA (Net Non-Performing Assets) | Value of NPAs after deducting provisions | Gross NPAs - Provisions |  Reveals potential losses if borrowers default, a better indicator of bank's financial health |

**Key Points**

* Banks aim to keep both GNPA and NNPA ratios low.
* High GNPA and NNPA ratios signal potential financial distress for a bank.
* Investors and regulators closely track these metrics to assess a bank's stability.

### NPA Impact

- NPA improve = Loan Portfolio quality of the bank will be better = Market sentiment will be good = Stock price will improve

## Datasets

### Internal Dataset

<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th>Variable Name</th>
      <th>Description</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Tot_Closed_T</td>
      <td>Total closed trade lines/accounts</td>
    </tr>
    <tr>
      <td>Tot_Active_TL</td>
      <td>Total active accounts</td>
    </tr>
    <tr>
      <td>Total_TL_opened_L6M</td>
      <td>Total accounts opened in last 6 Months</td>
    </tr>
    <tr>
      <td>Tot_TL_closed_L6M</td>
      <td>Total accounts closed in last 6 months</td>
    </tr>
    <tr>
      <td>pct_tl_open_L6M</td>
      <td>Percent accounts opened in last 6 months</td>
    </tr>
    <tr>
      <td>pct_tl_closed_L6M</td>
      <td>percent accounts closed in last 6 months</td>
    </tr>
    <tr>
      <td>pct_active_tl</td>
      <td>Percent active accounts</td>
    </tr>
    <tr>
      <td>pct_closed_tl</td>
      <td>Percent closed accounts</td>
    </tr>
    <tr>
      <td>Total_TL_opened_L12M</td>
      <td>Total accounts opened in last 12 Months</td>
    </tr>
    <tr>
      <td>Tot_TL_closed_L12M</td>
      <td>Total accounts closed in last 12 months</td>
    </tr>
    <tr>
      <td>pct_tl_open_L12M</td>
      <td>Percent accounts opened in last 12 months</td>
    </tr>
    <tr>
      <td>pct_tl_closed_L12M</td>
      <td>percent accounts closed in last 12 months</td>
    </tr>
    <tr>
      <td>Tot Missed Pmnt</td>
      <td>Total missed Payments</td>
    </tr>
    <tr>
      <td>Auto TL</td>
      <td>Count Automobile accounts</td>
    </tr>
    <tr>
      <td>CC TL</td>
      <td>Count of Credit card accounts</td>
    </tr>
    <tr>
      <td>Consumer_TL</td>
      <td>Count of Consumer goods accounts</td>
    </tr>
    <tr>
      <td>Gold TL</td>
      <td>Count of Gold loan accounts</td>
    </tr>
    <tr>
      <td>Home_TL</td>
      <td>Count of Housing loan accounts</td>
    </tr>
    <tr>
      <td>PLOTL</td>
      <td>Count of Personal loan accounts</td>
    </tr>
    <tr>
      <td>Secured_TL</td>
      <td>Count of secured accounts</td>
    </tr>
    <tr>
      <td>Unsecured_TL</td>
      <td>Count of unsecured accounts</td>
    </tr>
    <tr>
      <td>Other_TL</td>
      <td>Count of other accounts</td>
    </tr>
    <tr>
      <td>Age_Oldest_TL</td>
      <td>Age of oldest opened account</td>
    </tr>
    <tr>
      <td>Age_Newest_TL</td>
      <td>Age of newest opened account</td>
    </tr>
  </tbody>
</table>

### External Dataset (Cibil)

<table border="1">
  <thead>
    <tr>
      <th>#</th>
      <th>Variable Name</th>
      <th>Description</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>1</td>
      <td>time_since_recent_payment</td>
      <td>Time Since recent Payment made</td>
    </tr>
    <tr>
      <td>2</td>
      <td>time_since_first_deliquency</td>
      <td>Time since first Deliquency (missed payment)</td>
    </tr>
    <tr>
      <td>3</td>
      <td>time_since_recent_deliquency</td>
      <td>Time Since recent Delinquency</td>
    </tr>
    <tr>
      <td>4</td>
      <td>num_times_delinquent</td>
      <td>Number of times delinquent</td>
    </tr>
    <tr>
      <td>5</td>
      <td>max_delinquency_level</td>
      <td>Maximum delinquency level</td>
    </tr>
    <tr>
      <td>6</td>
      <td>max_recent_level_of_deliq</td>
      <td>Maximum recent level of delinquency</td>
    </tr>
    <tr>
      <td>7</td>
      <td>num_deliq_6mts</td>
      <td>Number of times delinquent in last 6 months</td>
    </tr>
    <tr>
      <td>8</td>
      <td>num_deliq_12mts</td>
      <td>Number of times delinquent in last 12 months</td>
    </tr>
    <tr>
      <td>9</td>
      <td>num_deliq_6_12mts</td>
      <td>Number of times delinquent between last 6 months and last 12 months</td>
    </tr>
    <tr>
      <td>10</td>
      <td>max_deliq_6mts</td>
      <td>Maximum delinquency level in last 6 months</td>
    </tr>
    <tr>
      <td>11</td>
      <td>max_deliq_12mts</td>
      <td>Maximum delinquency level in last 12 months</td>
    </tr>
    <tr>
      <td>12</td>
      <td>num_times_30p_dpd</td>
      <td>Number of times 30+ dpd</td>
    </tr>
    <tr>
      <td>13</td>
      <td>num_times_60p_dpd</td>
      <td>Number of times 60+ dpd</td>
    </tr>
    <tr>
      <td>14</td>
      <td>num_std</td>
      <td>Number of standard Payments</td>
    </tr>
    <tr>
      <td>15</td>
      <td>num_std_6mts</td>
      <td>Number of standard Payments in last 6 months</td>
    </tr>
    <tr>
      <td>16</td>
      <td>num_std_12mts</td>
      <td>Number of standard Payments in last 12 months</td>
    </tr>
    <tr>
      <td>17</td>
      <td>num_sub</td>
      <td>Number of sub standard payments - not making full payments</td>
    </tr>
    <tr>
      <td>18</td>
      <td>num_sub_6mts</td>
      <td>Number of sub standard payments in last 6 months</td>
    </tr>
    <tr>
      <td>19</td>
      <td>num_sub_12mts</td>
      <td>Number of sub standard payments in last 12 months</td>
    </tr>
    <tr>
      <td>20</td>
      <td>num_dbt</td>
      <td>Number of doubtful payments</td>
    </tr>
    <tr>
      <td>21</td>
      <td>num_dbt_6mts</td>
      <td>Number of doubtful payments in last 6 months</td>
    </tr>
    <tr>
      <td>22</td>
      <td>num_dbt_12mts</td>
      <td>Number of doubtful payments in last 12 months</td>
    </tr>
    <tr>
      <td>23</td>
      <td>num_Iss</td>
<td>Number of loss accounts</td>
</tr>
<tr>
<td>24</td>
<td>num_lss_6mts</td>
<td>Number of loss accounts in last 6 months</td>
</tr>
<tr>
<td>25</td>
<td>num_lss_12mts</td>
<td>Number of loss accounts in last 12 months</td>
</tr>
<tr>
<td>26</td>
<td>recent_level_of_deliq</td>
<td>Recent level of delinquency</td>
</tr>
<tr>
<td>27</td>
<td>tot_enq</td>
<td>Total enquiries</td>
</tr>
<tr>
<td>28</td>
<td>CC_enq</td>
<td>Credit card enquiries</td>
</tr>
<tr>
<td>29</td>
<td>CC_enq_L6m</td>
<td>Credit card enquiries in last 6 months</td>
</tr>
<tr>
<td>30</td>
<td>CC_enq_L12m</td>
<td>Credit card enquiries in last 12 months</td>
</tr>
<tr>
<td>31</td>
<td>PL_enq</td>
<td>Personal Loan enquiries</td>
</tr>
<tr>
<td>32</td>
<td>PL_enq_L6m</td>
<td>Personal Loan enquiries in last 6 months</td>
</tr>
<tr>
<td>33</td>
<td>PL_enq_L12m</td>
<td>Personal Loan enquiries in last 12 months</td>
</tr>
<tr>
<td>34</td>
<td>time_since_recent_enq</td>
<td>Time since recent enquiry</td>
</tr>
<tr>
<td>35</td>
<td>enq_L12m</td>
<td>Enquiries in last 12 months</td>
</tr>
<tr>
<td>36</td>
<td>enq_L6m</td>
<td>Enquiries in last 6 months</td>
</tr>
<tr>
<td>37</td>
<td>enq_L3m</td>
<td>Enquiries in last 3 months</td>
</tr>
<tr>
<td>38</td>
<td>MARITALSTATUS</td>
<td>Marital Status</td>
</tr>
<tr>
<td>39</td>
<td>EDUCATION</td>
<td>Education level</td>
</tr>
<tr>
<td>AGE</td>
<td>Age</td>
</tr>
<tr>
<td>41</td>
<td>GENDER</td>
<td>Gender</td>
</tr>
  <tr>
      <th>42</th>
      <td>NETMONTHLYINCOME</td>
      <td>Net monthly income</td>
    </tr>
      <tr>
      <th>43</th>
      <td>Time_With_Curr_Empr</td>
      <td>Time with current Employer</td>
    </tr>
    <tr>
      <th>44</th>
      <td>pct_of_active_TLs_ever</td>
      <td>Percent active accounts ever</td>
    </tr>
    <tr>
      <th>45</th>
      <td>pct_opened_TLs_L6m_of_L12m</td>
      <td>Percent accounts opened in last 6 months to last 12 months</td>
    </tr>
    <tr>
      <th>46</th>
      <td>pct_currentBal_all_TL</td>
      <td>Percent current balance of all accounts</td>
    </tr>
    <tr>
      <th>47</th>
      <td>CC_utilization</td>
      <td>Credit card utilization</td>
    </tr>
    <tr>
      <th>48</th>
      <td>CC_Flag</td>
      <td>Credit card Flag</td>
    </tr>
    <tr>
      <th>49</th>
      <td>PL_utilization</td>
      <td>Peronal Loan utilization</td>
    </tr>
    <tr>
      <th>50</th>
      <td>PL_Flag</td>
      <td>Personal Loan Flag</td>
    </tr>
    <tr>
      <th>51</th>
      <td>pct_PL_enq_L6m_of_L12m</td>
      <td>Percent enquiries PL in last 6 months to last 12 months</td>
    </tr>
    <tr>
      <th>52</th>
      <td>pct_CC_enq_L6m_of_L12m</td>
      <td>Percent enquiries CC in last 6 months to last 12 months</td>
    </tr>
    <tr>
      <th>53</th>
      <td>pct_PL_enq_L6m_of_ever</td>
      <td>Percent enquiries PL in last 6 months to last 6 months</td>
    </tr>
    <tr>
      <th>54</th>
      <td>pct_CC_enq_L6m_of_ever</td>
      <td>Percent enquiries CC in last 6 months to last 6 months</td>
    </tr>
    <tr>
      <th>55</th>
      <td>max_unsec_exposure_inPct</td>
      <td>Maximum unsecured exposure in percent</td>
    </tr>
    <tr>
      <th>56</th>
      <td>HL_Flag</td>
      <td>Housing Loan Flag</td>
    </tr>
    <tr>
      <th>57</th>
      <td>GL_Flag</td>
      <td>Gold Loan Flag</td>
    </tr>
    <tr>
      <th>58</th>
      <td>last_prod_enq2</td>
      <td>Lates product enquired for</td>
    </tr>
    <tr>
      <th>59</th>
      <td>first_prod_enq2</td>
      <td>First product enquired for</td>
    </tr>
    <tr>
      <th>60</th>
      <td>Credit_Score</td>
      <td>Applicant's credit score</td>
    </tr>
    <tr>
      <th>61</th>
      <td>Approved_Flag</td>
      <td>Priority levels</td>
    </tr>
</tbody>
</table>

In [1]:
!pip install matplotlib scikit-learn statsmodels openpyxl -U -q

In [2]:
# Import necessary libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.metrics import r2_score
from scipy.stats import chi2_contingency

from statsmodels.stats.outliers_influence import variance_inflation_factor
from sklearn.model_selection import train_test_split

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, precision_recall_fscore_support

import warnings
import os

In [3]:

# Load the dataset
a1 = pd.read_excel("./dataset/case_study1.xlsx")
a2 = pd.read_excel("./dataset/case_study2.xlsx")

df1 = a1.copy()
df2 = a2.copy()

In [4]:
df1

,PROSPECTID,Total_TL,Tot_Closed_TL,Tot_Active_TL,Total_TL_opened_L6M,Tot_TL_closed_L6M,pct_tl_open_L6M,pct_tl_closed_L6M,pct_active_tl,pct_closed_tl,...,CC_TL,Consumer_TL,Gold_TL,Home_TL,PL_TL,Secured_TL,Unsecured_TL,Other_TL,Age_Oldest_TL,Age_Newest_TL
0,1,5,4,1,0,0,0.000,0.00,0.200,0.800,...,0,0,1,0,4,1,4,0,72,18
1,2,1,0,1,0,0,0.000,0.00,1.000,0.000,...,0,1,0,0,0,0,1,0,7,7
2,3,8,0,8,1,0,0.125,0.00,1.000,0.000,...,0,6,1,0,0,2,6,0,47,2
3,4,1,0,1,1,0,1.000,0.00,1.000,0.000,...,0,0,0,0,0,0,1,1,5,5
4,5,3,2,1,0,0,0.000,0.00,0.333,0.667,...,0,0,0,0,0,3,0,2,131,32
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51331,51332,3,0,3,1,0,0.333,0.00,1.000,0.000,...,0,2,0,0,0,0,3,1,24,5
51332,51333,4,2,2,0,1,0.000,0.25,0.500,0.500,...,0,2,0,0,0,2,2,0,74,7
51333,51334,2,1,1,1,1,0.500,0.50,0.500,0.500,...,0,2,0,0,0,0,2,0,9,5
51334,51335,2,1,1,0,0,0.000,0.00,0.500,0.500,...,0,2,0,0,0,0,2,0,15,8
51335,51336,1,0,1,0,0,0.000,0.00,1.000,0.000,...,0,0,0,0,0,1,0,0,20,20

In [8]:
df1.columns

Index(['PROSPECTID', 'Total_TL', 'Tot_Closed_TL', 'Tot_Active_TL',
       'Total_TL_opened_L6M', 'Tot_TL_closed_L6M', 'pct_tl_open_L6M',
       'pct_tl_closed_L6M', 'pct_active_tl', 'pct_closed_tl',
       'Total_TL_opened_L12M', 'Tot_TL_closed_L12M', 'pct_tl_open_L12M',
       'pct_tl_closed_L12M', 'Tot_Missed_Pmnt', 'Auto_TL', 'CC_TL',
       'Consumer_TL', 'Gold_TL', 'Home_TL', 'PL_TL', 'Secured_TL',
       'Unsecured_TL', 'Other_TL', 'Age_Oldest_TL', 'Age_Newest_TL'],
      dtype='object')

In [5]:
df2

,PROSPECTID,time_since_recent_payment,time_since_first_deliquency,time_since_recent_deliquency,num_times_delinquent,max_delinquency_level,max_recent_level_of_deliq,num_deliq_6mts,num_deliq_12mts,num_deliq_6_12mts,...,pct_CC_enq_L6m_of_L12m,pct_PL_enq_L6m_of_ever,pct_CC_enq_L6m_of_ever,max_unsec_exposure_inPct,HL_Flag,GL_Flag,last_prod_enq2,first_prod_enq2,Credit_Score,Approved_Flag
0,1,549,35,15,11,29,29,0,0,0,...,0.0,0.0,0.0,13.333,1,0,PL,PL,696,P2
1,2,47,-99999,-99999,0,-99999,0,0,0,0,...,0.0,0.0,0.0,0.860,0,0,ConsumerLoan,ConsumerLoan,685,P2
2,3,302,11,3,9,25,25,1,9,8,...,0.0,0.0,0.0,5741.667,1,0,ConsumerLoan,others,693,P2
3,4,-99999,-99999,-99999,0,-99999,0,0,0,0,...,0.0,0.0,0.0,9.900,0,0,others,others,673,P2
4,5,583,-99999,-99999,0,-99999,0,0,0,0,...,0.0,0.0,0.0,-99999.000,0,0,AL,AL,753,P1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51331,51332,15,24,23,2,24,24,0,0,0,...,0.0,0.0,0.0,1.661,0,0,ConsumerLoan,ConsumerLoan,650,P4
51332,51333,57,-99999,-99999,0,-99999,0,0,0,0,...,0.0,0.0,0.0,0.520,0,0,others,others,702,P1
51333,51334,32,-99999,-99999,0,-99999,0,0,0,0,...,0.0,1.0,0.0,0.567,0,0,ConsumerLoan,others,661,P3
51334,51335,58,-99999,-99999,0,-99999,0,0,0,0,...,0.0,0.0,0.0,1.202,0,0,ConsumerLoan,others,686,P2
51335,51336,74,-99999,-99999,0,-99999,0,0,0,0,...,0.0,0.0,0.0,-99999.000,0,0,others,others,681,P2

In [9]:
df1 = df1.loc[df1['Age_Oldest_TL'] != -99999]

columns_to_be_removed = []

for i in df2.columns:
    if df2.loc[df2[i] == -99999].shape[0] > 10000:
        columns_to_be_removed.append(i)

In [10]:
df2 =df2.drop(columns_to_be_removed,axis=1)

In [11]:
df2

,PROSPECTID,time_since_recent_payment,num_times_delinquent,max_recent_level_of_deliq,num_deliq_6mts,num_deliq_12mts,num_deliq_6_12mts,num_times_30p_dpd,num_times_60p_dpd,num_std,...,pct_PL_enq_L6m_of_L12m,pct_CC_enq_L6m_of_L12m,pct_PL_enq_L6m_of_ever,pct_CC_enq_L6m_of_ever,HL_Flag,GL_Flag,last_prod_enq2,first_prod_enq2,Credit_Score,Approved_Flag
0,1,549,11,29,0,0,0,0,0,21,...,0.0,0.0,0.0,0.0,1,0,PL,PL,696,P2
1,2,47,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0,0,ConsumerLoan,ConsumerLoan,685,P2
2,3,302,9,25,1,9,8,0,0,10,...,0.0,0.0,0.0,0.0,1,0,ConsumerLoan,others,693,P2
3,4,-99999,0,0,0,0,0,0,0,5,...,0.0,0.0,0.0,0.0,0,0,others,others,673,P2
4,5,583,0,0,0,0,0,0,0,53,...,0.0,0.0,0.0,0.0,0,0,AL,AL,753,P1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51331,51332,15,2,24,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0,0,ConsumerLoan,ConsumerLoan,650,P4
51332,51333,57,0,0,0,0,0,0,0,6,...,0.0,0.0,0.0,0.0,0,0,others,others,702,P1
51333,51334,32,0,0,0,0,0,0,0,0,...,1.0,0.0,1.0,0.0,0,0,ConsumerLoan,others,661,P3
51334,51335,58,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0,0,ConsumerLoan,others,686,P2
51335,51336,74,0,0,0,0,0,0,0,18,...,0.0,0.0,0.0,0.0,0,0,others,others,681,P2

In [13]:
df2.shape

(51336, 54)

In [14]:
for i in df2.columns:
    df2 = df2.loc[df2[i] != -99999]

In [15]:
# Checking common column names
for i in list(df1.columns):
    if i in list(df2.columns):
        print(i)

PROSPECTID

In [16]:
df = pd.merge(df1,df2,how="inner",left_on=['PROSPECTID'],right_on=['PROSPECTID'])

In [17]:
df

,PROSPECTID,Total_TL,Tot_Closed_TL,Tot_Active_TL,Total_TL_opened_L6M,Tot_TL_closed_L6M,pct_tl_open_L6M,pct_tl_closed_L6M,pct_active_tl,pct_closed_tl,...,pct_PL_enq_L6m_of_L12m,pct_CC_enq_L6m_of_L12m,pct_PL_enq_L6m_of_ever,pct_CC_enq_L6m_of_ever,HL_Flag,GL_Flag,last_prod_enq2,first_prod_enq2,Credit_Score,Approved_Flag
0,1,5,4,1,0,0,0.000,0.00,0.200,0.800,...,0.0,0.0,0.000,0.0,1,0,PL,PL,696,P2
1,2,1,0,1,0,0,0.000,0.00,1.000,0.000,...,0.0,0.0,0.000,0.0,0,0,ConsumerLoan,ConsumerLoan,685,P2
2,3,8,0,8,1,0,0.125,0.00,1.000,0.000,...,0.0,0.0,0.000,0.0,1,0,ConsumerLoan,others,693,P2
3,5,3,2,1,0,0,0.000,0.00,0.333,0.667,...,0.0,0.0,0.000,0.0,0,0,AL,AL,753,P1
4,6,6,5,1,0,0,0.000,0.00,0.167,0.833,...,1.0,0.0,0.429,0.0,1,0,ConsumerLoan,PL,668,P3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42059,51332,3,0,3,1,0,0.333,0.00,1.000,0.000,...,0.0,0.0,0.000,0.0,0,0,ConsumerLoan,ConsumerLoan,650,P4
42060,51333,4,2,2,0,1,0.000,0.25,0.500,0.500,...,0.0,0.0,0.000,0.0,0,0,others,others,702,P1
42061,51334,2,1,1,1,1,0.500,0.50,0.500,0.500,...,1.0,0.0,1.000,0.0,0,0,ConsumerLoan,others,661,P3
42062,51335,2,1,1,0,0,0.000,0.00,0.500,0.500,...,0.0,0.0,0.000,0.0,0,0,ConsumerLoan,others,686,P2
42063,51336,1,0,1,0,0,0.000,0.00,1.000,0.000,...,0.0,0.0,0.000,0.0,0,0,others,others,681,P2

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42064 entries, 0 to 42063
Data columns (total 79 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   PROSPECTID                  42064 non-null  int64
 1   Total_TL                    42064 non-null  int64
 2   Tot_Closed_TL               42064 non-null  int64
 3   Tot_Active_TL               42064 non-null  int64
 4   Total_TL_opened_L6M         42064 non-null  int64
 5   Tot_TL_closed_L6M           42064 non-null  int64
 6   pct_tl_open_L6M             42064 non-null  float64
 7   pct_tl_closed_L6M           42064 non-null  float64
 8   pct_active_tl               42064 non-null  float64
 9   pct_closed_tl               42064 non-null  float64
 10  Total_TL_opened_L12M        42064 non-null  int64
 11  Tot_TL_closed_L12M          42064 non-null  int64
 12  pct_tl_open_L12M            42064 non-null  float64
 13  pct_tl_closed_L12M          42064 non-null  float64
 14  Tot_Missed_Pmnt             42064 non-null  int64
 15  Auto_TL                     42064 non-null  int64
 16  CC_TL                       42064 non-null  int64
 17  Consumer_TL                 42064 non-null  int64
 18  Gold_TL                     42064 non-null  int64
 19  Home_TL                     42064 non-null  int64
 20  PL_TL                       42064 non-null  int64
 21  Secured_TL                  42064 non-null  int64
 22  Unsecured_TL                42064 non-null  int64
 23  Other_TL                    42064 non-null  int64
 24  Age_Oldest_TL               42064 non-null  int64
 25  Age_Newest_TL               42064 non-null  int64
 26  time_since_recent_payment   42064 non-null  int64
 27  num_times_delinquent        42064 non-null  int64
 28  max_recent_level_of_deliq   42064 non-null  int64
 29  num_deliq_6mts              42064 non-null  int64
 30  num_deliq_12mts             42064 non-null  int64
 31  num_deliq_6_12mts           42064 non-null  int64
 32  num_times_30p_dpd           42064 non-null  int64
 33  num_times_60p_dpd           42064 non-null  int64
 34  num_std                     42064 non-null  int64
 35  num_std_6mts                42064 non-null  int64
 36  num_std_12mts               42064 non-null  int64
 37  num_sub                     42064 non-null  int64
 38  num_sub_6mts                42064 non-null  int64
 39  num_sub_12mts               42064 non-null  int64
 40  num_dbt                     42064 non-null  int64
 41  num_dbt_6mts                42064 non-null  int64
 42  num_dbt_12mts               42064 non-null  int64
 43  num_lss                     42064 non-null  int64
 44  num_lss_6mts                42064 non-null  int64
 45  num_lss_12mts               42064 non-null  int64
 46  recent_level_of_deliq       42064 non-null  int64
 47  tot_enq                     42064 non-null  int64
 48  CC_enq                      42064 non-null  int64
 49  CC_enq_L6m                  42064 non-null  int64
 50  CC_enq_L12m                 42064 non-null  int64
 51  PL_enq                      42064 non-null  int64
 52  PL_enq_L6m                  42064 non-null  int64
 53  PL_enq_L12m                 42064 non-null  int64
 54  time_since_recent_enq       42064 non-null  int64
 55  enq_L12m                    42064 non-null  int64
 56  enq_L6m                     42064 non-null  int64
 57  enq_L3m                     42064 non-null  int64
 58  MARITALSTATUS               42064 non-null  object
 59  EDUCATION                   42064 non-null  object
 60  AGE                         42064 non-null  int64
 61  GENDER                      42064 non-null  object
 62  NETMONTHLYINCOME            42064 non-null  int64
 63  Time_With_Curr_Empr         42064 non-null  int64
 64  pct_of_active_TLs_ever      42064 non-null  float64
 65  pct_opened_TLs_L6m_of_L12m  42064 non-null  float64
 66  pct_currentBal_all_TL       42064 non-null  float64
 67  CC_Flag                     42064 non-null  int64
 68  PL_Flag                     42064 non-null  int64
 69  pct_PL_enq_L6m_of_L12m      42064 non-null  float64
 70  pct_CC_enq_L6m_of_L12m      42064 non-null  float64
 71  pct_PL_enq_L6m_of_ever      42064 non-null  float64
 72  pct_CC_enq_L6m_of_ever      42064 non-null  float64
 73  HL_Flag                     42064 non-null  int64
 74  GL_Flag                     42064 non-null  int64
 75  last_prod_enq2              42064 non-null  object
 76  first_prod_enq2             42064 non-null  object
 77  Credit_Score                42064 non-null  int64
 78  Approved_Flag               42064 non-null  object
dtypes: float64(13), int64(60), object(6)
memory usage: 25.4+ MB

In [20]:
df.isnull().sum().sum()

0

In [23]:
df.columns

Index(['PROSPECTID', 'Total_TL', 'Tot_Closed_TL', 'Tot_Active_TL',
       'Total_TL_opened_L6M', 'Tot_TL_closed_L6M', 'pct_tl_open_L6M',
       'pct_tl_closed_L6M', 'pct_active_tl', 'pct_closed_tl',
       'Total_TL_opened_L12M', 'Tot_TL_closed_L12M', 'pct_tl_open_L12M',
       'pct_tl_closed_L12M', 'Tot_Missed_Pmnt', 'Auto_TL', 'CC_TL',
       'Consumer_TL', 'Gold_TL', 'Home_TL', 'PL_TL', 'Secured_TL',
       'Unsecured_TL', 'Other_TL', 'Age_Oldest_TL', 'Age_Newest_TL',
       'time_since_recent_payment', 'num_times_delinquent',
       'max_recent_level_of_deliq', 'num_deliq_6mts', 'num_deliq_12mts',
       'num_deliq_6_12mts', 'num_times_30p_dpd', 'num_times_60p_dpd',
       'num_std', 'num_std_6mts', 'num_std_12mts', 'num_sub', 'num_sub_6mts',
       'num_sub_12mts', 'num_dbt', 'num_dbt_6mts', 'num_dbt_12mts', 'num_lss',
       'num_lss_6mts', 'num_lss_12mts', 'recent_level_of_deliq', 'tot_enq',
       'CC_enq', 'CC_enq_L6m', 'CC_enq_L12m', 'PL_enq', 'PL_enq_L6m',
       'PL_enq_L12m', 'time_since_recent_enq', 'enq_L12m', 'enq_L6m',
       'enq_L3m', 'MARITALSTATUS', 'EDUCATION', 'AGE', 'GENDER',
       'NETMONTHLYINCOME', 'Time_With_Curr_Empr', 'pct_of_active_TLs_ever',
       'pct_opened_TLs_L6m_of_L12m', 'pct_currentBal_all_TL', 'CC_Flag',
       'PL_Flag', 'pct_PL_enq_L6m_of_L12m', 'pct_CC_enq_L6m_of_L12m',
       'pct_PL_enq_L6m_of_ever', 'pct_CC_enq_L6m_of_ever', 'HL_Flag',
       'GL_Flag', 'last_prod_enq2', 'first_prod_enq2', 'Credit_Score',
       'Approved_Flag'],
      dtype='object')

In [24]:
for i in ['MARITALSTATUS', 'EDUCATION', 'GENDER', 'last_prod_enq2', 'first_prod_enq2']:
    chi2, pval, dof, expected = chi2_contingency(pd.crosstab (df[i], df['Approved_Flag']))
    print(i, '---', pval)

MARITALSTATUS --- 3.578180861038862e-233
EDUCATION --- 2.6942265249737532e-30
GENDER --- 1.907936100186563e-05
last_prod_enq2 --- 0.0
first_prod_enq2 --- 7.84997610555419e-287

In [26]:
#VIF for numerical columns
numeric_columns = []
for i in df.columns:
    if df[i].dtype != 'object' and i not in ['PROSPECTID', 'Approved_Flag']:
        numeric_columns.append(i)

## Multicollinearity vs. Correlation: A Detailed Breakdown

| Feature | Multicollinearity | Correlation |
|---|---|---|
| **Definition** | Occurs when two or more independent variables in a regression model are highly correlated with each other. |  Indicates a linear relationship between two variables. The strength of the association is measured by the correlation coefficient (ranging from -1 to +1). |
| **Impact on Regression Analysis** | Makes it difficult to interpret the coefficients of individual variables. Increases the variance of the estimated coefficients, making them less precise and potentially leading to unreliable results. | Does not directly affect the validity of the regression model, but can affect the precision of coefficient estimates. High correlation can make it difficult to determine the individual contribution of each variable to the model. |
| **Detection Methods** |  - Variance Inflation Factor (VIF)  - Eigenvalues of the correlation matrix  - Examining the condition number | Correlation coefficient |
| **Consequences** |  - Coefficients with high standard errors  - Coefficients with unexpected signs  - Difficulty isolating the effects of individual variables |  - Reduced precision of coefficient estimates  - Potential for misleading interpretations |
| **Remedies** |  - Dropping a collinear variable (carefully chosen to minimize information loss)  - Combining collinear variables  - Using regularization techniques (e.g., ridge regression, LASSO) |  - Depending on the severity, may not require specific action. If problematic, consider dropping a highly correlated variable or transforming the data. |
| **Example** | Trying to model house price while including both square footage and living area. These variables are likely highly correlated. | Income and education level might be correlated, but including both in a model might still be useful depending on the research question. |

**Additional Points:**

* **Multicollinearity is a concern specifically in regression analysis**, whereas correlation is a broader concept applicable to any two variables.
* **Correlation does not imply causation**. Just because two variables are correlated doesn't mean one causes the other.
* **There is no single threshold for VIF to determine multicollinearity**. A common rule of thumb is that a VIF > 5 indicates a potential problem, but the decision often depends on the specific analysis.

I hope this table clarifies the distinction between multicollinearity and correlation!

Absolutely! Here's a breakdown of multicollinearity vs. correlation, including why they matter in data analysis:

**Correlation**

* **What it is:**  A statistical measure of the linear relationship between two variables. It tells you the strength and direction of the association.
* **Values:** Ranges from -1 (perfect negative correlation) to +1 (perfect positive correlation), with 0 indicating no correlation.
* **Example:** Height and weight are often positively correlated. Taller people tend to weigh more.

**Multicollinearity**

* **What it is:** Occurs in multiple regression when two or more independent variables (predictors) are highly correlated with each other.  This means the predictors can, to some extent, be used to predict each other.
* **Problem:** Multicollinearity makes it hard to determine the *individual* effect of each predictor on the outcome variable. This leads to:
    * **Unstable coefficients:** Estimates of how much the outcome variable changes per unit change in a predictor can fluctuate wildly with small data changes.
    * **Inflated standard errors:** It becomes more difficult to determine if a predictor's effect is statistically significant.
    * **Overfitting** Models might perform well on training data but have poor real-world prediction capability.

**Why Correlation Can Be Misleading with Multicollinearity**

Simple correlation between two variables might be low, but  that doesn't rule out multicollinearity. A group of other predictors, when combined, might strongly predict one of the variables you thought were uncorrelated.  This is more difficult to see just by looking at pairs of correlations.

**Key Points**

* Correlation is about the relationship between *two* variables.
* Multicollinearity involves *multiple* variables being highly interrelated.
* Multicollinearity is primarily a concern in regression-like models where you're trying to isolate the impact of individual variables.

**Let me know if you'd like more details on how to detect multicollinearity or ways to deal with it!**

Certainly! VIF, or Variance Inflation Factor, is a diagnostic tool used in regression analysis to quantify the severity of multicollinearity. 

**What does VIF measure?**

VIF measures how much the variance of an estimated regression coefficient is inflated due to multicollinearity. In simpler terms, it tells you how much more uncertain the coefficient for a particular variable is because other variables in the model are already capturing some of its effect. 

**How is VIF calculated?**

VIF is calculated for each independent variable in a regression model. Here's the formula:

VIF_j = 1 / (1 - R_j^2)

Where:

* VIF_j:  The variance inflation factor for the jth independent variable. 
* R_j^2: The R-squared value obtained from a regression model where the jth independent variable is regressed against all other independent variables in the model. 

**Interpreting VIF values:**

* A VIF of 1 indicates no multicollinearity, and the coefficient's variance is not inflated.
* A VIF greater than 1 suggests some degree of multicollinearity. The higher the VIF, the greater the inflation of the variance and the less precise the coefficient estimate.
* There's no single threshold for a "high" VIF.  Common rules of thumb suggest:
    * VIF > 5 indicates moderate multicollinearity.
    * VIF > 10 indicates severe multicollinearity, and the coefficient estimates might be unreliable.

**Important points about VIF:**

* VIF is just a guide, and other factors can influence the impact of multicollinearity.
* A high VIF for one variable doesn't necessarily mean there's a problem for other variables in the model. 
* VIF should be used alongside other diagnostics to assess multicollinearity.

**What to do if you find high VIF?**

If you find high VIF for some variables, here are some approaches you can consider:

* **Remove highly correlated variables:** Analyze the correlations between variables and consider removing one or more with very high correlation with others.
* **Combine variables:** If variables have a natural interpretation together, you could create a new combined variable.
* **Dimensionality reduction techniques:** Techniques like Principal Component Analysis (PCA) can help reduce the number of variables while retaining most of the information.
* **Regularization:** Techniques like Ridge Regression can help shrink coefficient estimates and reduce the impact of multicollinearity.

By understanding VIF and how to address multicollinearity, you can improve the reliability and interpretability of your regression models.

In [27]:
# VIF sequentially check
vif_data = df[numeric_columns]
total_columns = vif_data.shape[1]
columns_to_be_kept = []
column_index = 0

for i in range(0, total_columns):
    vif_value = variance_inflation_factor(vif_data, column_index)
    print(column_index, '---', vif_value)
    
    if vif_value <= 6:
        columns_to_be_kept.append(numeric_columns[i])
        column_index = column_index + 1
    else:
        vif_data = vif_data.drop([numeric_columns[i]], axis=1)

/home/kavaiyaeducation/.local/lib/python3.9/site-packages/statsmodels/stats/outliers_influence.py:198: RuntimeWarning: divide by zero encountered in scalar divide
  vif = 1. / (1. - r_squared_i)

0 --- inf

/home/kavaiyaeducation/.local/lib/python3.9/site-packages/statsmodels/stats/outliers_influence.py:198: RuntimeWarning: divide by zero encountered in scalar divide
  vif = 1. / (1. - r_squared_i)

0 --- inf
0 --- 11.320180023967996
0 --- 8.363698035000327
0 --- 6.520647877790928
0 --- 5.149501618212625
1 --- 2.611111040579735

/home/kavaiyaeducation/.local/lib/python3.9/site-packages/statsmodels/stats/outliers_influence.py:198: RuntimeWarning: divide by zero encountered in scalar divide
  vif = 1. / (1. - r_squared_i)

2 --- inf
2 --- 1788.7926256209232
2 --- 8.601028256477228
2 --- 3.8328007921530785
3 --- 6.099653381646727
3 --- 5.581352009642762
4 --- 1.985584353098778

/home/kavaiyaeducation/.local/lib/python3.9/site-packages/statsmodels/stats/outliers_influence.py:198: RuntimeWarning: divide by zero encountered in scalar divide
  vif = 1. / (1. - r_squared_i)

5 --- inf
5 --- 4.809538302819343
6 --- 23.270628983464636
6 --- 30.595522588100053
6 --- 4.3843464059655854
7 --- 3.0646584155234238
8 --- 2.898639771299252
9 --- 4.377876915347324
10 --- 2.207853583695844
11 --- 4.916914200506864
12 --- 5.214702030064725
13 --- 3.3861625024231476
14 --- 7.840583309478997
14 --- 5.255034641721438

/home/kavaiyaeducation/.local/lib/python3.9/site-packages/statsmodels/stats/outliers_influence.py:198: RuntimeWarning: divide by zero encountered in scalar divide
  vif = 1. / (1. - r_squared_i)

15 --- inf
15 --- 7.380634506427232
15 --- 1.421005001517573
16 --- 8.083255010190323
16 --- 1.6241227524040114
17 --- 7.257811920140003
17 --- 15.59624383268298
17 --- 1.825857047132431
18 --- 1.5080839450032664
19 --- 2.172088834824578
20 --- 2.623397553527229
21 --- 2.2959970812106167
22 --- 7.360578319196446
22 --- 2.1602387773102554
23 --- 2.8686288267891467
24 --- 6.458218003637277
24 --- 2.8474118865638265
25 --- 4.7531981562840855
26 --- 16.22735475594825
26 --- 6.424377256363877
26 --- 8.887080381808687
26 --- 2.3804746142952666
27 --- 8.609513476514548
27 --- 13.06755093547673
27 --- 3.5000400566546555
28 --- 1.9087955874813773
29 --- 17.006562234161628
29 --- 10.730485153719197
29 --- 2.3538497522950275
30 --- 22.104855915136433
30 --- 2.7971639638512924
31 --- 3.424171203217696
32 --- 10.175021454450912
32 --- 6.408710354561296
32 --- 1.001151196262563
33 --- 3.069197305397274
34 --- 2.8091261600643724
35 --- 20.249538381980678
35 --- 15.864576541593774
35 --- 1.8331649740532168
36 --- 1.5680839909542044
37 --- 1.9307572353811677
38 --- 4.331265056645247
39 --- 9.390334396150173

In [28]:
# check Anova for columns_to_be_kept
from scipy.stats import f_oneway

columns_to_be_kept_numerical = []

for i in columns_to_be_kept:
    a = list(df[i])
    b = list(df['Approved_Flag'])

group_P1 = [value for value, group in zip(a, b) if group == 'P1']
group_P2 = [value for value, group in zip(a, b) if group == 'P2']
group_P3 = [value for value, group in zip(a, b) if group == 'P3']
group_P4 = [value for value, group in zip(a, b) if group == 'P4']

f_statistic, p_value = f_oneway(group_P1, group_P2, group_P3, group_P4)

In [29]:
# VIF sequentially check
vif_data = df[numeric_columns]
total_columns = vif_data.shape[1]
columns_to_be_kept = []
column_index = 0

for i in range(0, total_columns):
    vif_value = variance_inflation_factor(vif_data, column_index)
    print(column_index, '----', vif_value)
    
    if vif_value <= 6:
        columns_to_be_kept.append(numeric_columns[i])
        column_index = column_index + 1
    else:
        vif_data = vif_data.drop([numeric_columns[i]], axis=1)

/home/kavaiyaeducation/.local/lib/python3.9/site-packages/statsmodels/stats/outliers_influence.py:198: RuntimeWarning: divide by zero encountered in scalar divide
  vif = 1. / (1. - r_squared_i)

0 ---- inf

/home/kavaiyaeducation/.local/lib/python3.9/site-packages/statsmodels/stats/outliers_influence.py:198: RuntimeWarning: divide by zero encountered in scalar divide
  vif = 1. / (1. - r_squared_i)

0 ---- inf
0 ---- 11.320180023967996
0 ---- 8.363698035000327
0 ---- 6.520647877790928
0 ---- 5.149501618212625
1 ---- 2.611111040579735

/home/kavaiyaeducation/.local/lib/python3.9/site-packages/statsmodels/stats/outliers_influence.py:198: RuntimeWarning: divide by zero encountered in scalar divide
  vif = 1. / (1. - r_squared_i)

2 ---- inf
2 ---- 1788.7926256209232
2 ---- 8.601028256477228
2 ---- 3.8328007921530785
3 ---- 6.099653381646727
3 ---- 5.581352009642762
4 ---- 1.985584353098778

/home/kavaiyaeducation/.local/lib/python3.9/site-packages/statsmodels/stats/outliers_influence.py:198: RuntimeWarning: divide by zero encountered in scalar divide
  vif = 1. / (1. - r_squared_i)

5 ---- inf
5 ---- 4.809538302819343
6 ---- 23.270628983464636
6 ---- 30.595522588100053
6 ---- 4.3843464059655854
7 ---- 3.0646584155234238
8 ---- 2.898639771299252
9 ---- 4.377876915347324
10 ---- 2.207853583695844
11 ---- 4.916914200506864
12 ---- 5.214702030064725
13 ---- 3.3861625024231476
14 ---- 7.840583309478997
14 ---- 5.255034641721438

/home/kavaiyaeducation/.local/lib/python3.9/site-packages/statsmodels/stats/outliers_influence.py:198: RuntimeWarning: divide by zero encountered in scalar divide
  vif = 1. / (1. - r_squared_i)

15 ---- inf
15 ---- 7.380634506427232
15 ---- 1.421005001517573
16 ---- 8.083255010190323
16 ---- 1.6241227524040114
17 ---- 7.257811920140003
17 ---- 15.59624383268298
17 ---- 1.825857047132431
18 ---- 1.5080839450032664
19 ---- 2.172088834824578
20 ---- 2.623397553527229
21 ---- 2.2959970812106167
22 ---- 7.360578319196446
22 ---- 2.1602387773102554
23 ---- 2.8686288267891467
24 ---- 6.458218003637277
24 ---- 2.8474118865638265
25 ---- 4.7531981562840855
26 ---- 16.22735475594825
26 ---- 6.424377256363877
26 ---- 8.887080381808687
26 ---- 2.3804746142952666
27 ---- 8.609513476514548
27 ---- 13.06755093547673
27 ---- 3.5000400566546555
28 ---- 1.9087955874813773
29 ---- 17.006562234161628
29 ---- 10.730485153719197
29 ---- 2.3538497522950275
30 ---- 22.104855915136433
30 ---- 2.7971639638512924
31 ---- 3.424171203217696
32 ---- 10.175021454450912
32 ---- 6.408710354561296
32 ---- 1.001151196262563
33 ---- 3.069197305397274
34 ---- 2.8091261600643724
35 ---- 20.249538381980678
35 ---- 15.864576541593774
35 ---- 1.8331649740532168
36 ---- 1.5680839909542044
37 ---- 1.9307572353811677
38 ---- 4.331265056645247
39 ---- 9.390334396150173